CREATE TABLE COMPANY_TYPE (
TYPE_CODE Long AUTO_INCREMENT primary key,
TYPE_NAME varchar
);

CREATE TABLE COMPANY_LOCATION (
LOCATION_CODE Long AUTO_INCREMENT primary key,
LOCATION_NAME varchar
);

CREATE TABLE MEMBER (
ID Long AUTO_INCREMENT PRIMARY KEY,
NAME varchar(255),
PASSWORD varchar(255),
GENDER varchar(255),
COMPANY_NAME varchar(255),
TYPE_CODE Long,
LOCATION_CODE Long
);